<a href="https://colab.research.google.com/github/pjhbrain/python101/blob/main/1_1_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 주피터노트북


In [9]:
1

1

# 파이썬

## 셀 타입

- 코드
- 마크다운/텍스트

## 셀 모드

- 편집
- 명령


## 셀 실행

- Shift + Enter 현재 셀 실행하고 아래 셀 선택
- Ctrl + Enter 현재 셀 실행하고 현재 셀 선택
- Alt + Enter (colab) 현재 셀 실행하고 아래에 새로운 코드 셀 생성

## 단축키
- 구글 코랩에서는 노트북 단축키를 사용자가 지정할 수 있으며, 일반적인 주피터노트북과 달리 셀 편집모드에서도 단축키를 통해 셀 잘라내기, 새로운 셀 생성 등 셀 편집이 가능

- '메뉴-도구-단축키'에서 설정
    - 셀 잘라내기 Ctrl + m, x
    - 셀 복사하기 Ctrl + m, c
    - 셀 붙이기 Ctrl + v
    - 셀 삭제 Ctrl + m, d
    - 위에 새로운 셀 삽입하기 Ctrl + m, a
    - 아래에 새로운 셀 삽입하기 Ctrl + m, b
    - 셀 타입 코드로 변환 Ctrl + m, y
    - 셀 타입 마크다운으로 변환 Ctrl + m, m
    - 실행 취소 Ctrl + m, z
    - 단축키 확인 Ctrl + m, x
    - 선택된 여러 셀 병합 Ctrl + Shift + m
    - 현재 커서 위치에서 셀 분할 Ctrl + m, -
    - 주석 설정/해제 Ctrl + /

In [10]:
import sys

print(sys.version)
print(sys.version_info)

3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
sys.version_info(major=3, minor=10, micro=12, releaselevel='final', serial=0)


In [ ]:
# PEP8 스타일
# https://www.python.org/dev/peps/pep-0008/

In [ ]:
# 탭 대신 스페이스를 사용해서 들여쓰기
# 라인 길이는 79개 문자 이하
# 긴 식을 다음 줄에 이어서 쓸 경우에는 일반적인 들여쓰기보다 4 스페이스를 더 들여서 씀
# 파일 안에서 각 함수와 클래스 사이에는 빈 줄을 두 줄 넣기
# 클래스 안에서 메서드와 메서드 사이에는 빈 줄을 한 줄
# 딕셔너리에서 키와 콜론 사이에는 공백을 넣지 않고, 한 줄 안에 키와 값을 같이 넣는 경우에는 콜론 다음에 스페이스 하나 넣기
# 변수 대입에서 = 전후에는 스페이스를 하나씩만 넣기

# 기본 자료형

## 숫자, 참/거짓, 문자열

In [11]:
1

1

In [12]:
type(1)

int

In [13]:
type(1.0)

float

In [14]:
True

True

In [ ]:
False, True

(False, True)

In [15]:
type(True)

bool

In [17]:
'true'

'true'

In [ ]:
type('python')

str

In [ ]:
type("python")

str

In [ ]:
type('a')

str

In [ ]:
type("p")

str

In [ ]:
type('python'), type(.5)

(str, float)

In [23]:
a = 1
b = 2

In [25]:
print(a)
print(b)

1
2


In [28]:
a == 5

True

In [27]:
a = 5
b = (a == 5)
c = 'KOR'
print(a, b, c)

5 True KOR


- 더하기

In [29]:
4 + 5

9

In [30]:
'KOR' + '15'

'KOR15'

In [31]:
'KOR' + 15

TypeError: can only concatenate str (not "int") to str

- 수는 수끼리, 문자열은 문자열끼리 더할 수 있음
- 자료형 변경은 str(), float(), int() 등을 이용

In [32]:
'KOR' + str(15)

'KOR15'

In [33]:
print(type(15))
print(type(str(15)))

<class 'int'>
<class 'str'>


In [ ]:
float(str(15))

15.0

- bool 자료형에 사칙연산을 적용할 경우 False는 0, True는 1의 값을 갖는 것으로 처리됨

In [ ]:
4 + True

5

In [ ]:
4 + False

4

In [ ]:
4 * True

4

In [ ]:
4 * False

0

In [34]:
int(True)

1

In [ ]:
int(False)

0

- 문자열 포맷 f-string

In [39]:
a = 2
b = 'two'
print(a, b)

2 two


In [40]:
print('abc')
print(f'abc {a}')

abc
abc 2


In [41]:
print(f'{a} is {b}')

2 is two


In [43]:
print(f'{a:.10f} is {b}')

2.0000000000 is two


In [ ]:
print(f'{a:.2f} is {b:}')

2.00 is two


In [ ]:
print(f'{b:} is {a:.2f}')

two is 2.00


In [44]:
print(f'{b:} is {10000:,.2f}')

two is 10,000.00


- 문자열에서 공백 없애기

In [ ]:
" abc ".lstrip()

'abc '

In [ ]:
" abc ".rstrip()

' abc'

In [ ]:
" abc ".strip()

'abc'

In [ ]:
"abc".strip('a')

'bc'

## 리스트

In [45]:
a = [1, 2, 3]
b = ['one', 'two', 'three']

In [46]:
print(a)
print(b)

[1, 2, 3]
['one', 'two', 'three']


In [47]:
type(a)

list

In [50]:
print(4 + 3)
print(4 * 3)

7
12


In [51]:
a * 2

[1, 2, 3, 1, 2, 3]

In [52]:
b * 2

['one', 'two', 'three', 'one', 'two', 'three']

In [53]:
a + b

[1, 2, 3, 'one', 'two', 'three']

In [54]:
a + 5

TypeError: can only concatenate list (not "int") to list

In [ ]:
a + 'four'

TypeError: can only concatenate list (not "str") to list

- list에 숫자 또는 문자열을 더하는 연산이 정의되어 있지 않으므로 오류발생

In [ ]:
a + [5]

[1, 2, 3, 5]

In [55]:
print(b)
b.append('four')
print(b)

['one', 'two', 'three']
['one', 'two', 'three', 'four']


In [57]:
print(b)
b.append([1, 2, 3])
print(b)

['one', 'two', 'three', 'four']
['one', 'two', 'three', 'four', [1, 2, 3]]


In [58]:
b

['one', 'two', 'three', 'four', [1, 2, 3]]

In [60]:
print(b[0])
print(b[1])
print(b[4])
print(b[-1])

one
two
[1, 2, 3]
[1, 2, 3]


- 숫자로 이루어진 리스트의 각 항목에 숫자를 더하기 위해서는 list comprehension이나 for-loop 이용

In [61]:
a = [1, 2, 3]

In [62]:
for i in a:
  print(i)

1
2
3


In [65]:
[i for i in a]

[1, 2, 3]

In [68]:
[i + 1 for i in a]

[2, 3, 4]

- 뒤에 다룰 넘파이 ndarray 자료형은 숫자형 자료 리스트처럼 생겼으나, 숫자 하나를 더할 수 있음

In [69]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


- 리스트에 있는 문자열을 특정 기호로 연결

In [72]:
b = ['one', 'two', 'three']
b

['one', 'two', 'three']

In [73]:
' '.join(b)

'one two three'

- 파이썬 인덱스는 0부터 시작!!

In [74]:
a

[1, 2, 3]

In [ ]:
a[0]

1

In [76]:
a[0:2]

[1, 2, 3]

In [77]:
a[:2]

[1, 2]

- list의 마지막 항목의 인덱스는 -1

In [ ]:
a[-1]

3

In [78]:
a = ['KOR', 'USA', 'CHN']
print(a[0], a[-1], a[:2], a[-2:])

KOR CHN ['KOR', 'USA'] ['USA', 'CHN']


- 주피터노트북에서 긴 리스트는 세로로 표시되지만, %pprint 명령어로 옵션 변경 가능,
- print() 명령어를 사용하면, 긴 리스트도 가로로 표시

In [ ]:
a * 4

['KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN',
 'KOR',
 'USA',
 'CHN']

In [ ]:
print(a * 4)

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']


In [ ]:
from pprint import pprint

In [ ]:
%pprint

Pretty printing has been turned OFF


In [ ]:
a * 4

['KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN', 'KOR', 'USA', 'CHN']

In [ ]:
data = {'age': 30,
 'education': {'grad': {'degree': 'MSc',
                        'university': 'ABC University',
                        'year': 2015},
               'undergrad': {'degree': 'BSc',
                             'university': 'XYZ University',
                             'year': 2012}},
 'hobbies': ['reading', 'cycling', 'hiking'],
 'name': 'Alice',
 'work_experience': [{'company': 'Company A', 'position': 'Engineer', 'years': 3},
                     {'company': 'Company B',
                      'position': 'Senior Engineer',
                      'years': 2}]}

In [ ]:
print(data)

{'age': 30, 'education': {'grad': {'degree': 'MSc', 'university': 'ABC University', 'year': 2015}, 'undergrad': {'degree': 'BSc', 'university': 'XYZ University', 'year': 2012}}, 'hobbies': ['reading', 'cycling', 'hiking'], 'name': 'Alice', 'work_experience': [{'company': 'Company A', 'position': 'Engineer', 'years': 3}, {'company': 'Company B', 'position': 'Senior Engineer', 'years': 2}]}


In [ ]:
pprint(data)

{'age': 30,
 'education': {'grad': {'degree': 'MSc',
                        'university': 'ABC University',
                        'year': 2015},
               'undergrad': {'degree': 'BSc',
                             'university': 'XYZ University',
                             'year': 2012}},
 'hobbies': ['reading', 'cycling', 'hiking'],
 'name': 'Alice',
 'work_experience': [{'company': 'Company A',
                      'position': 'Engineer',
                      'years': 3},
                     {'company': 'Company B',
                      'position': 'Senior Engineer',
                      'years': 2}]}


In [ ]:
%pprint

Pretty printing has been turned ON


- 문자열 리스트의 각 항목을 따옴표 없이 print()하기 위해 리스트이름 앞에 * 입력
- print()가 출력하는 각 항목 사이를 구분하기 위해 sep = '기호'를 지정
- print()가 마지막에 출력할 내용을 지정하기 위해 end = '기호'를 지정(기본은 '\n')

In [79]:
a

['KOR', 'USA', 'CHN']

In [80]:
print(a)

['KOR', 'USA', 'CHN']


In [81]:
print(*a)

KOR USA CHN


In [83]:
print(*a, sep = '  ')

KOR  USA  CHN


- list comprehension

In [84]:
['KOR', 'USA', 'CHN'] - ['CHN', 'AUS']

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [87]:
[i for i in ['KOR', 'USA', 'CHN'] if i not in ['CHN', 'AUS']]

['KOR', 'USA']

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN', 'AUS']]

['KOR', 'USA']

- set() 이용

In [89]:
print(['KOR', 'USA', 'CHN'])
print(set(['KOR', 'USA', 'CHN']))

print(type(['KOR', 'USA', 'CHN']))
print(type(set(['KOR', 'USA', 'CHN'])))

['KOR', 'USA', 'CHN']
{'KOR', 'USA', 'CHN'}
<class 'list'>
<class 'set'>


In [ ]:
set(['KOR', 'USA', 'CHN']), set(['CHN', 'AUS'])

({'CHN', 'KOR', 'USA'}, {'AUS', 'CHN'})

In [90]:
set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS'])

{'KOR', 'USA'}

In [95]:
list(set(['KOR', 'USA', 'CHN']).intersection(set(['CHN', 'AUS'])))

['CHN']

In [ ]:
list(set(['KOR', 'USA', 'CHN']) - set(['CHN', 'AUS']))

['KOR', 'USA']

- 문자열 리스트 항목별로 문자열 더하기

In [ ]:
[s + ':g' for s in ['KOR', 'USA', 'CHN']]

['KOR:g', 'USA:g', 'CHN:g']

In [97]:
['국가명: ' + i for i in ['대한민국', '미국', '중국']]

['국가명: 대한민국', '국가명: 미국', '국가명: 중국']

- 문자열은 각 캐릭터(123.../abc.../가나다... 등)로 구성된 리스트

In [98]:
a = 'abcde'

In [99]:
a[0]

'a'

In [100]:
a[:3]

'abc'

In [ ]:
a[-2:]

'de'

In [101]:
"가나다라마"[:2]

'가나'

- 이전 실행한 출력셀의 값 불러오기

In [ ]:
_

'가나'

In [ ]:
Out[92]

'가나'

In [ ]:
_94

'가나'

- range()로 수 리스트 만들기
    - range(s, e, i): 처음 위치(생략시 0), 마지막 위치(리스트에 포함 안됨), 수 간격(생략시 1)
    - for-loop 등에서 주로 이용하며, 순서대로 해당하는 값만 필요하므로 실제 리스트를 생성하지 않음
        - 리스트 생성시 메모리 공간을 크게 차지할 수 있으므로 비효율적임
    - 리스트를 생성하기 위해서는 list() 함수 실행

In [ ]:
for i in range(5):  # range(0, 5, 1)
    print(i)

0
1
2
3
4


In [ ]:
for i in range(5, 0, -2):  # range(0, 5, 1)
    print(i)

5
3
1


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 딕셔너리

In [102]:
iso = {'US':'USA', 'KR':'KOR', 'JP':'JPN', 'CN':'CHN'}

In [104]:
kr_en = {'서울특별시':'SE', '경기도':'GG', '인청광역시':'IC'}

In [105]:
iso['US']

'USA'

In [ ]:
iso['KR']

'KOR'

In [106]:
iso.keys()

dict_keys(['US', 'KR', 'JP', 'CN'])

In [108]:
for i in list(iso.keys()):
  print(i)

US
KR
JP
CN


In [110]:
for i in list(iso.keys()):
  print(i, iso[i])

US USA
KR KOR
JP JPN
CN CHN


In [ ]:
iso.values()

dict_values(['USA', 'KOR', 'JPN', 'CHN'])

In [112]:
iso['AU']

KeyError: 'AU'

In [113]:
iso['AU'] = 'AUS'

In [114]:
iso

{'US': 'USA', 'KR': 'KOR', 'JP': 'JPN', 'CN': 'CHN', 'AU': 'AUS'}

- dict, zip으로 딕셔너리 만들기

In [115]:
{'한국':'KR', '미국':'US', '일본':'JP'}

{'한국': 'KR', '미국': 'US', '일본': 'JP'}

In [117]:
print(['한국', '미국', '일본'])
print(['KR', 'US', 'JP'])

['한국', '미국', '일본']
['KR', 'US', 'JP']


In [ ]:
dict(zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']))

{'한국': 'KR', '미국': 'US', '일본': 'JP'}

In [118]:
for i in ['한국', '미국', '일본']:
  print(i)

한국
미국
일본


In [119]:
for i, ii in zip(['한국', '미국', '일본'], ['KR', 'US', 'JP']):
  print(i, ii)

한국 KR
미국 US
일본 JP


In [ ]:
import pandas as pd
countries = pd.Series(['South Korea', 'United States', 'North Korea'])
print(countries)

0      South Korea
1    United States
2      North Korea
dtype: object


In [ ]:
cdict = {'South Korea':'KR', 'United States':'US'}
countries.replace(cdict)

0             KR
1             US
2    North Korea
dtype: object

### 튜플

In [122]:
a = [1, 2, 3]

print(a)
print(a[0])
print(type(a))

a[0] = 10

print(a)

[1, 2, 3]
1
<class 'list'>
[10, 2, 3]


In [123]:
a = (1, 2, 3)

print(a)
print(a[0])
print(type(a))

a[0] = 10

print(a)

(1, 2, 3)
1
<class 'tuple'>


TypeError: 'tuple' object does not support item assignment

In [124]:
a = 5
b = 10
c = 15

In [125]:
a, b, c = 5, 10, 15

In [ ]:
print(a, b, c)

5 10 15


In [126]:
a, b = b, a
print(a, b)

10 5


In [ ]:
c = 1, 2, 3
print(type(c))

<class 'tuple'>


## 연습문제

- 아래 국가명 리스트와 연도 리스트를 이용하여 국가명_연도 문자열을 생성하라
- 아래 리스트와 인덱스를 이용하여 일본과 중국을 제외한 국가에 대해서만 국가명_연도 문자열을 생성하라

In [ ]:
countries = ['KOR', 'USA', 'JPN', 'CHN', 'AUS', 'MEX']
year = [17, 18, 19, 20]

- 아래 문자열 리스트에서 숫자를 나타내는 문자열만 선택하여 리스트를 생성하라(힌트, isnumeric()/isdigit(), strip() 이용)

In [ ]:
strings = ['KOR', '한국', '15', "True", '1000', '-5']

# 문법

- 파이썬에서 for loop, if 구문, 함수 정의시 indentation(스페이스 4개) 이용
    - 주피터노트북에서 tab은 스페이스 4개를 입력
- 코드작성의 자유도가 낮은 대신, 가독성이 매우 높아짐


```
<C>
if (i=1; i<=n; i++) {
  printf("%d\n", i);
}

<matlab>
for i = 1:n
    disp(i)
end

<python>
for i = range(1, n+1)
    disp(i)
```

## definition

In [127]:
def sum_two_numbers(a, b):
    return a + b

In [129]:
sum_two_numbers(5, 2)

7

In [140]:
def cal_numbers(a, b):
    return set([a + b, a * b])

In [141]:
cal_numbers(3, 4)

{7, 12}

In [ ]:
def sum_three_numbers(a, b, c=4):
    return a + 2*b + c

In [ ]:
sum_three_numbers(1, 2, 0)

5

In [ ]:
sum_three_numbers(1, 2)

9

In [ ]:
sum_three_numbers(b=2, a=1)

9

In [ ]:
sum_two_numbers2 = lambda x, y: x + y

In [ ]:
sum_two_numbers2(1, 2)

3

## for-loop, if-else

In [144]:
countries = ['KOR', 'USA', 'CHN']

for c in countries:
  if c == 'KOR':
    print(c)
  else:
    print('KOR X')

KOR
KOR X
KOR X


In [ ]:
countries = ['KOR', 'USA', 'CHN']
for c in countries:
    if c == 'KOR':
        print(c, 'is my country.')
    else:
        print(c)

KOR is my country.
USA
CHN


## continue, break, pass

In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        continue
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2
3 is not 2


In [ ]:
for i in range(4):    # [0, 1, 2, 3]
    if i==2:
        break
    else:
        print(f'{i} is not 2')


0 is not 2
1 is not 2


In [ ]:
if True:
  print('True')
else:
    print('False')

True


In [ ]:
if True:
    pass
else:
    print('False')

## list comprehension v. for-loop
- 앞 리스트에서 뒤 리스트에 속한 항목 제외하기

In [ ]:
[s for s in ['KOR', 'USA', 'CHN'] if s not in ['CHN','AUS']]

['KOR', 'USA']

In [ ]:
clist = []
for c in ['KOR', 'USA', 'CHN']:
    if c not in ['CHN', 'AUS']:
        clist = clist + [c] # clist.append(c)
clist

['KOR', 'USA']

# 라이브러리: numpy
- ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의
- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

In [149]:
list_1d = [1, 2, 3]
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(list_1d)
print(list_2d)
print(list_2d[1])

[1, 2, 3]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[4, 5, 6]


In [151]:
import numpy as np

In [145]:
import numpy
import numpy as np
print(numpy.sin(0), np.sin(0))

0.0 0.0


In [154]:
print(sin(0))

NameError: name 'sin' is not defined

In [ ]:
print(np.pi)

3.141592653589793


In [155]:
a = np.pi
print(f'a')
print(f'{a}')
print(f'{a:.2f}')

a
3.141592653589793
3.14


## 인덱스

- 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [158]:
list1 = [[1, 2 ,3], [2, 3, 4]]
print(type(list1))
array1 = np.array(list1)
print(type(array1))

<class 'list'>
<class 'numpy.ndarray'>


In [164]:
a0 = [[1, 2 ,3], [2, 3, 4]]
a1 = np.array([[1, 2 ,3], [2, 3, 4]])

In [161]:
print(a1)
print(np.shape(a1))

[[1 2 3]
 [2 3 4]]
(2, 3)


In [165]:
print(a1[0, 0])

1


In [167]:
print(a0[0][0])

1


In [170]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [171]:
a1[:, 0]

array([1, 2])

In [ ]:
a1[:, 0]

array([1, 2])

In [ ]:
a1[0, :]

array([1, 2, 3])

## 통계량 및 연산

In [174]:
# Q1. 아래 n, c 리스트를 이용해서 key가 국가이고, value가 대륙인 딕셔너리를 만들어 보세요

n = ['한국', '일본', '중국', '영국', '프랑스', '미국', '캐나다']
c = ['아시아', '아시아', '아시아', '유럽', '유럽', '아메리카', '아메리카']

# Q2. 1부터 10까지 제곱 수의 리스트를 만들어 보세요
# 참고 3의 제곱은 3**2
# [1**2, 2**2, 3**2, ...] 이렇게 말고.. 리스트컴프리헨션을 이용해서

In [176]:
d = dict(zip(n, c))
d = {i: ii for i, ii in zip(n, c)}
a = [i**2 for i in range(1, 10+1)]

print(d)
print(a)

{'한국': '아시아', '일본': '아시아', '중국': '아시아', '영국': '유럽', '프랑스': '유럽', '미국': '아메리카', '캐나다': '아메리카'}
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [177]:
v = np.array([1, 2, 3])
print(v)

[1 2 3]


In [178]:
type(v)

numpy.ndarray

In [179]:
m = np.array([[1, 2], [3, 4]])
m

array([[1, 2],
       [3, 4]])

In [180]:
print(v.mean(), v.std(), v.max())

2.0 0.816496580927726 3


In [182]:
np.sin([0, np.pi/2, np.pi])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
np.sin([0, np.pi / 2, np.pi])

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a[0,0] = -1

In [ ]:
a

array([[-1,  2],
       [ 3,  4]])

In [ ]:
a[0] = 0
a

array([[0, 0],
       [3, 4]])

In [ ]:
a[:, 1] = [5, 6]
print(a)

[[0 5]
 [3 6]]


In [183]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [184]:
v1 + 1

array([2, 3, 4])

In [185]:
v1 * 2

array([2, 4, 6])

In [186]:
v1 ** 2

array([1, 4, 9])

In [ ]:
np.log(v1)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.exp(v1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## dimension
- ndarray 간의 +, -, *, / 등 사칙연산은 elementwise이므로 모양이 서로 같아야함

In [187]:
v1

array([1, 2, 3])

In [188]:
v1.shape

(3,)

In [189]:
a2 = np.array([[1, 2], [1, 3], [1, 4]])

In [ ]:
a2

array([[1, 2],
       [1, 3],
       [1, 4]])

In [190]:
a2.shape

(3, 2)

In [ ]:
a1

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
a1 * a2

ValueError: ignored

In [ ]:
v1.shape, v2.shape

((3,), (3,))

In [191]:
print(v1)
print(v2)

[1 2 3]
[-1  0  1]


In [192]:
v1 + v2

array([0, 2, 4])

In [193]:
v1 * v2

array([-1,  0,  3])

In [195]:
a1 = [1, 2, 3]
a2 = [4, 5, 6]

a1 + a2

[1, 2, 3, 4, 5, 6]

In [194]:
v1.dot(v2)

2

In [ ]:
m

array([[1, 2],
       [3, 4]])

In [197]:
m

array([[1, 2],
       [3, 4]])

In [196]:
m.T

array([[1, 3],
       [2, 4]])

In [ ]:
v = np.array([1, 0])
m.dot(v)

array([1, 3])

In [ ]:
v.dot(m)

array([1, 2])

In [ ]:
print('{} \n\n {}'.format(a1, a2.T))

[[1 2 3]
 [2 3 4]] 

 [[1 1 1]
 [2 3 4]]


In [ ]:
print(a1 * a2.T)

[[ 1  2  3]
 [ 4  9 16]]


## matrix operation

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [ ]:
a1.dot(a2)

array([[ 6, 20],
       [ 9, 29]])

In [ ]:
np.dot(a1, a2)

array([[ 6, 20],
       [ 9, 29]])

In [ ]:
A = np.dot(a1, a2)
print(A)

[[ 6 20]
 [ 9 29]]


- 역행렬: numpy.linalg.inv() 함수 이용

In [ ]:
print(np.linalg.inv(a1.dot(a2)))

[[-4.83333333  3.33333333]
 [ 1.5        -1.        ]]


In [ ]:
from numpy.linalg import inv

In [ ]:
inv(a1.dot(a2))

array([[-4.83333333,  3.33333333],
       [ 1.5       , -1.        ]])

In [ ]:
np.identity(a1.shape[0])

array([[1., 0.],
       [0., 1.]])

- 레온티에프 역행렬

In [ ]:
np.linalg.inv(np.identity(A.shape[0]) - A)

array([[ 0.7  , -0.5  ],
       [-0.225,  0.125]])

## random sample

- 동일한 랜덤표본을 얻기 위해서는 numpy.random.seed(n) (예: n=1) 실행
    - seed()를 지정하지 않는 경우 파이썬은 현재 날짜-시간을 이용하여 seed() 지정

In [198]:
import numpy as np

In [204]:
rsn = np.random.randn(10)
rsn

array([-0.51781153, -1.5047307 ,  0.90491299,  1.24824343,  1.16282077,
       -1.17126944,  0.12411254,  2.5729199 , -0.32607792,  0.56877728])

In [200]:
rsn

array([-0.41481307, -0.08651379,  1.74024386, -0.31105128,  0.4194477 ,
        0.75404455,  0.7031126 , -0.79205272,  1.5648141 ,  0.55920155])

In [205]:
rsi = np.random.randint(1, 10, 10)

In [206]:
rsi

array([4, 3, 2, 9, 7, 7, 6, 2, 3, 4])

In [ ]:
rsu = np.random.uniform(-1, 1, 10)

In [ ]:
rsu

array([ 0.98340165, -0.82718337, -0.89835087, -0.48222867, -0.21196053,
       -0.8024412 ,  0.56554767,  0.10349785,  0.12036892, -0.9000916 ])

In [209]:
np.random.seed(2)
np.random.randn(3)

array([-0.41675785, -0.05626683, -2.1361961 ])

In [ ]:
np.random.seed(2)
np.random.randn(3)

array([-0.41675785, -0.05626683, -2.1361961 ])

In [ ]:
np.random.seed(1)
np.random.randn(3)

array([ 1.62434536, -0.61175641, -0.52817175])

In [210]:
# 함수 이름은 cal_xy
# input: x, y
# output: (x + y) ** 2

# cal_xy(2, 3)

def cal_xy(x, y):
  return (x + y) ** 2

print(cal_xy(2, 3))

25


In [ ]:
# Q1. x + y + x * y + x ** 2

In [ ]:
def func_test(x, y):
    return x + y + x * y + x ** 2

print(func_test(1, 2))

6


In [ ]:
# Q2. 딕셔너리

In [ ]:
a1 = ['a', 'b', 'c', 'd', 'e']
a2 = list(range(5))

dict(zip(a1, a2))

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4}

In [ ]:
# Q3. 리스트 컴프리헨션

In [ ]:
a = list(range(2, 10))
[i ** 2 for i in a]

[4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
# Q4. np.array 제곱

In [ ]:
np.array(a) ** 2

array([ 4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Q5. 반복문 출력

In [ ]:
for i in range(1, 11):
    print(i ** 2)

1
4
9
16
25
36
49
64
81
100


In [ ]:
# 반복문 출력 조건

In [ ]:
for i in range(1, 11):
    if i == 5:
        continue
    else:
        print(i ** 2)

1
4
9
16
36
49
64
81
100
