<a href="https://colab.research.google.com/github/heegeunyoon/python101/blob/main/1_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy ndarray 개요

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [ ]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))
print(f'array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원')

array1: 1차원, array2: 1차원, array3: 1차원
array1: 1차원, array2: 1차원, array3: 1차원


In [ ]:
array3

array([1., 2., 3.])

In [ ]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [ ]:
sequence_array = np.arange(10)

print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [ ]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

In [ ]:
array1.reshape(4,3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

### indexing

* 단일값 추출

In [ ]:
# 1에서 부터 9 까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

In [ ]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

In [ ]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

* Slicing

In [ ]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

In [ ]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

In [ ]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

* fancy indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

* Boolean indexing

In [ ]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

In [ ]:
array1d > 5

In [ ]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

In [ ]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬:', org_array)
# np.sort( )로 정렬
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


In [ ]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc)

In [ ]:
array2d = np.array([[8, 12],
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

* 정렬 행렬의 인덱스 반환

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

In [ ]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

In [ ]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

* 전치 행렬

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

# 라이브러리: numpy
- ndarray는 행(row)과 열(column) 보다 첫번째 차원, 두번째 차원, 세번째 차원 등으로 정의
- 필요한 경우 matrix 자료형을 사용할 수 있으나 활용도가 낮음
- ndarray자료형을 이용하여 일반적인 matrix연산을 모두 할 수 있음
- 2-dim ndarray에서 행(row)처럼 보이는 것은 첫번째 차원임

In [ ]:
list_1d = [1, 2, 3]
list_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

print(list_1d)
print(list_2d)
print(list_2d[1])

In [ ]:
import numpy as np

In [ ]:
import numpy
import numpy as np
print(numpy.sin(0), np.sin(0))

In [ ]:
print(sin(0))

In [ ]:
print(np.pi)

In [ ]:
a = np.pi
print(f'a')
print(f'{a}')
print(f'{a:.2f}')

## 인덱스

- 특정 열(두번째 차원)에 접근하기 위해서는 콜론(:)을 첫번째 인덱스 자리에 입력

In [ ]:
list1 = [[1, 2 ,3], [2, 3, 4]]
print(type(list1))
array1 = np.array(list1)
print(type(array1))

In [ ]:
a0 = [[1, 2 ,3], [2, 3, 4]]
a1 = np.array([[1, 2 ,3], [2, 3, 4]])

In [ ]:
print(a1)
print(np.shape(a1))

In [ ]:
print(a1[0, 0])

In [ ]:
print(a0[0][0])

In [ ]:
a1

In [ ]:
a1[:, 0]

In [ ]:
a1[:, 0]

In [ ]:
a1[0, :]

## 통계량 및 연산

In [ ]:
# Q1. 아래 n, c 리스트를 이용해서 key가 국가이고, value가 대륙인 딕셔너리를 만들어 보세요

n = ['한국', '일본', '중국', '영국', '프랑스', '미국', '캐나다']
c = ['아시아', '아시아', '아시아', '유럽', '유럽', '아메리카', '아메리카']

# Q2. 1부터 10까지 제곱 수의 리스트를 만들어 보세요
# 참고 3의 제곱은 3**2
# [1**2, 2**2, 3**2, ...] 이렇게 말고.. 리스트컴프리헨션을 이용해서

In [ ]:
d = dict(zip(n, c))
d = {i: ii for i, ii in zip(n, c)}
a = [i**2 for i in range(1, 10+1)]

print(d)
print(a)

In [ ]:
v = np.array([1, 2, 3])
print(v)

In [ ]:
type(v)

In [ ]:
m = np.array([[1, 2], [3, 4]])
m

In [ ]:
print(v.mean(), v.std(), v.max())

In [ ]:
np.sin([0, np.pi/2, np.pi])

In [ ]:
np.sin([0, np.pi / 2, np.pi])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
a

In [ ]:
a[0,0] = -1

In [ ]:
a

In [ ]:
a[0] = 0
a

In [ ]:
a[:, 1] = [5, 6]
print(a)

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.array([-1, 0, 1])

In [ ]:
v1 + 1

In [ ]:
v1 * 2

In [ ]:
v1 ** 2

In [ ]:
np.log(v1)

In [ ]:
np.exp(v1)

## dimension
- ndarray 간의 +, -, *, / 등 사칙연산은 elementwise이므로 모양이 서로 같아야함

In [ ]:
v1

In [ ]:
v1.shape

In [ ]:
a2 = np.array([[1, 2], [1, 3], [1, 4]])

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a1

In [ ]:
a1 * a2

In [ ]:
v1.shape, v2.shape

In [ ]:
print(v1)
print(v2)

In [ ]:
v1 + v2

In [ ]:
v1 * v2

In [ ]:
a1 = [1, 2, 3]
a2 = [4, 5, 6]

a1 + a2

In [ ]:
v1.dot(v2)

In [ ]:
m

In [ ]:
m

In [ ]:
m.T

In [ ]:
v = np.array([1, 0])
m.dot(v)

In [ ]:
v.dot(m)

In [ ]:
print('{} \n\n {}'.format(a1, a2.T))

In [ ]:
print(a1 * a2.T)

## matrix operation

- numpy array로 생성된 객체는 ndarray 클래스의 메소드와 속성을 가짐
- transpose, dot product 등

In [ ]:
a1.dot(a2)

In [ ]:
np.dot(a1, a2)

In [ ]:
A = np.dot(a1, a2)
print(A)

- 역행렬: numpy.linalg.inv() 함수 이용

In [ ]:
print(np.linalg.inv(a1.dot(a2)))

In [ ]:
from numpy.linalg import inv

In [ ]:
inv(a1.dot(a2))

In [ ]:
np.identity(a1.shape[0])

- 레온티에프 역행렬

In [ ]:
np.linalg.inv(np.identity(A.shape[0]) - A)

## random sample

- 동일한 랜덤표본을 얻기 위해서는 numpy.random.seed(n) (예: n=1) 실행
    - seed()를 지정하지 않는 경우 파이썬은 현재 날짜-시간을 이용하여 seed() 지정

In [ ]:
import numpy as np

In [ ]:
rsn = np.random.randn(10)
rsn

In [ ]:
rsn

In [ ]:
rsi = np.random.randint(1, 10, 10)

In [ ]:
rsi

In [ ]:
rsu = np.random.uniform(-1, 1, 10)

In [ ]:
rsu

In [ ]:
np.random.seed(2)
np.random.randn(3)

In [ ]:
np.random.seed(2)
np.random.randn(3)

In [ ]:
np.random.seed(1)
np.random.randn(3)

In [ ]:
# 함수 이름은 cal_xy
# input: x, y
# output: (x + y) ** 2

# cal_xy(2, 3)

def cal_xy(x, y):
  return (x + y) ** 2

print(cal_xy(2, 3))

In [ ]:
# Q1. x + y + x * y + x ** 2

In [ ]:
def func_test(x, y):
    return x + y + x * y + x ** 2

print(func_test(1, 2))

In [ ]:
# Q2. 딕셔너리

In [ ]:
a1 = ['a', 'b', 'c', 'd', 'e']
a2 = list(range(5))

dict(zip(a1, a2))

In [ ]:
# Q3. 리스트 컴프리헨션

In [ ]:
a = list(range(2, 10))
[i ** 2 for i in a]

In [ ]:
# Q4. np.array 제곱

In [ ]:
np.array(a) ** 2

In [ ]:
# Q5. 반복문 출력

In [ ]:
for i in range(1, 11):
    print(i ** 2)

In [ ]:
# 반복문 출력 조건

In [ ]:
for i in range(1, 11):
    if i == 5:
        continue
    else:
        print(i ** 2)